#!/bin/bash

if [ -f /opt/apb/bin/activate ] ; then
 source /opt/apb/bin/activate
fi

echo "apb:x:$UID:$UID:apb:/home/apb:/bin/bash" >> /etc/passwd
sudo groupadd apb -g $UID
sudo usermod -a -G apb apb

gid=$(stat -c '%g' /var/run/docker.sock)
if [[ "0" == "$gid" ]]; then
  group=root
else
  group=docker
  sudo groupadd $group -g $gid
fi
sudo usermod -a -G $group apb

command="apb $@"
sg $group -c "$command"
