#!/bin/bash

if [ -f /opt/apb/bin/activate ] ; then
 source /opt/apb/bin/activate
fi

echo "apb:x:$UID:$UID:apb:/home/apb:/bin/bash" >> /etc/passwd
sudo groupadd apb -g $UID
sudo usermod -a -G apb apb

if ! [[ "${MINISHIFT_REGISTRY}" == "" ]]; then
  gid=$(stat -c '%g' ${DOCKER_CERT_PATH}/ca.pem)
else
  gid=$(stat -c '%g' /var/run/docker.sock)
fi

if GROUP=$(getent group -i $gid); then
  group=$(echo $GROUP | awk -F ":" '{ print $1 }')
else
  group=docker
  sudo groupadd $group -g $gid
fi
sudo usermod -a -G $group apb

command="apb $@"
sg $group -c "$command"
