.TH apb 1

.SH NAME
apb \- A tool for assisting in building and packaging APBs.
.SH SYNOPSIS
.B apb
[\fBOPTIONAL ARGUMENT\fR]
[\fBSUBCOMMAND\fR]

.SH DESCRIPTION
.B apb
This command is used to prepare and build an APB meta-container.
.SH OPTIONAL ARGUMENTS
.TP
.BR \-h ", " \-\-help 
Display the help message and exit.
.TP
.BR \-\-debug
Enable debug output.
.TP
.BR \-p ", " \-\-project \ \fIPATH\fR
Specify a path to your project. Defaults to CWD.

.SH SUBCOMMANDS
.TP
.BR help
Display the help message.
.TP
.BR prepare
Prepare an ansible-container project for APB packaging.
.TP
.BR build
Build and package APB container.
